services:
  - type: web
    name: youtube-transcript-chat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    pythonVersion: 3.10.12
